# Development values override
services:
  app:
    restart: "no"
    volumes:
      - .:/app:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  php:
    restart: "no"
    volumes:
      - .:/app:ro
