# Base compose file (production)
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/dockerfile
      target: app
    ports:
      - "80:80"
  php:
    restart: always
    build:
      context: .
      dockerfile: ./docker/dockerfile-php
