# Base app image
FROM nginx:alpine as app_base

COPY docker/nginx/site.conf /etc/nginx/conf.d/default.conf

# App image
FROM app_base AS app

WORKDIR /app

COPY ./*.php      .
COPY ./*.ico      .
COPY ./public     ./public